### ISSUE TITLE
Optionally perform package signing during upload

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-upload#2]
Some of the code from https://github.com/commercialhaskell/sig-tool should move into this repository. Idea would be:
1. Store user preference on package signing in the config file
2. If user has not expressed a preference on package signing, prompt for an answer
3. If user has elected to sign packages, sign and upload to signature archive _before_ uploading to Hackage
   - Motivation: Hackage uploads fail (or pretend to fail) very often. Even if the upload fails, having an extra signature into the signature archive is not detrimental

Pinging @chrisdone as well

**Comment by dysinger** [comment]
I asked this on slack before re-reading the description (above):

re: signing packages on `stack upload`.  do we want to make signing a default & just warn if they don't have GPG installed or can't sign because they don't have a signing key? or do we want to make it a flag on `stack upload`? con: if people have to add extra flags they might forget or not do it.

**Comment by dysinger** [comment]
I would like to be more aggressive about "encouraging" people to sign packages by warning if they can't sign.
